openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /user/info:
    get:
      operationId: listUsers
      description: ''
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
      tags:
      - user
  /user/groups:
    get:
      operationId: listGroups
      description: ''
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
          description: ''
      tags:
      - user
  /elections/:
    get:
      operationId: listElections
      description: ''
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ElectionProxy'
          description: ''
      tags:
      - elections
  /elections/{id}/:
    get:
      operationId: retrieveElection
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this Election.
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Election'
          description: ''
      tags:
      - elections
  /auth/otp/request:
    post:
      operationId: createRequestOneTimePassword
      description: Request One Time Email Code Login View
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - auth
  /auth/otp/verify:
    post:
      operationId: createValidateOneTimePassword
      description: Validate One Time Email Code Login View
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - auth
  /auth/token/register:
    post:
      operationId: createRegister
      description: Register users gateway
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
      tags:
      - auth
  /auth/token/login:
    post:
      operationId: createLogin
      description: Login users gateway
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
          description: ''
      tags:
      - auth
  /auth/token/logout:
    post:
      operationId: createLogout
      description: Logout user
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - auth
  /elections/create:
    post:
      operationId: createCreateElection
      description: Create election gateway
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateElection'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateElection'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateElection'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateElection'
          description: ''
      tags:
      - elections
  /elections/{id}/recordVote:
    post:
      operationId: createRecordVote
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordVote'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RecordVote'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RecordVote'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecordVote'
          description: ''
      tags:
      - elections
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        token:
          type: string
          readOnly: true
        groups:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            required:
            - id
            - name
        last_login:
          type: string
          format: date-time
          nullable: true
        first_name:
          type: string
          maxLength: 128
        last_name:
          type: string
          maxLength: 128
        email:
          type: string
          format: email
          maxLength: 254
        phone_number:
          type: string
          nullable: true
          maxLength: 16
        date_joined:
          type: string
          format: date-time
          readOnly: true
      required:
      - groups
      - email
    Group:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
      - id
      - name
    ElectionProxy:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 256
        description:
          type: string
          nullable: true
          maxLength: 2048
        from_date:
          type: string
          format: date-time
        to_date:
          type: string
          format: date-time
        status:
          type: string
          readOnly: true
      required:
      - title
      - from_date
      - to_date
    Election:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        status:
          type: string
          readOnly: true
        vote_options:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              title:
                type: string
                maxLength: 256
              description:
                type: string
                nullable: true
                maxLength: 2048
            required:
            - title
          readOnly: true
        can_vote:
          type: string
          readOnly: true
        creator:
          type: string
          readOnly: true
        can_see_results:
          type: string
          readOnly: true
        title:
          type: string
          maxLength: 256
        description:
          type: string
          nullable: true
          maxLength: 2048
        can_choose_multiple_options:
          type: boolean
        from_date:
          type: string
          format: date-time
        to_date:
          type: string
          format: date-time
        associated_groups:
          type: array
          items:
            type: integer
          description: Groups that can vote in this election
      required:
      - title
      - from_date
      - to_date
    Register:
      type: object
      properties:
        first_name:
          type: string
          maxLength: 128
        last_name:
          type: string
          maxLength: 128
        email:
          type: string
          format: email
          maxLength: 254
        phone_number:
          type: string
          nullable: true
          maxLength: 16
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - email
      - password
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
      - email
      - password
    CreateElection:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 256
        description:
          type: string
          maxLength: 2048
        associated_groups:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            required:
            - id
            - name
        can_choose_multiple_options:
          type: boolean
        from_date:
          type: string
          format: date-time
        to_date:
          type: string
          format: date-time
        options:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
                maxLength: 256
              description:
                type: string
                nullable: true
                maxLength: 2048
            required:
            - title
      required:
      - title
      - description
      - associated_groups
      - can_choose_multiple_options
      - from_date
      - to_date
      - options
    RecordVote:
      type: object
      properties:
        election:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            status:
              type: string
              readOnly: true
            vote_options:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    readOnly: true
                  title:
                    type: string
                    maxLength: 256
                  description:
                    type: string
                    nullable: true
                    maxLength: 2048
                required:
                - title
              readOnly: true
            can_vote:
              type: string
              readOnly: true
            creator:
              type: string
              readOnly: true
            can_see_results:
              type: string
              readOnly: true
            title:
              type: string
              maxLength: 256
            description:
              type: string
              nullable: true
              maxLength: 2048
            can_choose_multiple_options:
              type: boolean
            from_date:
              type: string
              format: date-time
            to_date:
              type: string
              format: date-time
            associated_groups:
              type: array
              items:
                type: integer
              description: Groups that can vote in this election
          required:
          - title
          - from_date
          - to_date
          readOnly: true
        voter:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            first_name:
              type: string
              maxLength: 128
            last_name:
              type: string
              maxLength: 128
          readOnly: true
        date_voted:
          type: string
          format: date-time
          readOnly: true
