export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const RESET_AUTH = 'RESET_AUTH';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_ELECTION_LIST_REQUEST = 'GET_ELECTION_LIST_REQUEST';
export const GET_ELECTION_LIST_SUCCESS = 'GET_ELECTION_LIST_SUCCESS';
export const GET_ELECTION_LIST_FAILURE = 'GET_ELECTION_LIST_FAILURE';

export const GET_ELECTION_REQUEST = 'GET_ELECTION_REQUEST';
export const GET_ELECTION_SUCCESS = 'GET_ELECTION_SUCCESS';
export const GET_ELECTION_FAILURE = 'GET_ELECTION_FAILURE';

export const RECORD_VOTE_REQUEST = 'RECORD_VOTE_REQUEST';
export const RECORD_VOTE_SUCCESS = 'RECORD_VOTE_SUCCESS';
export const RECORD_VOTE_FAILURE = 'RECORD_VOTE_FAILURE';

export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';

