# Generated by Django 4.1.7 on 2023-11-10 00:27

import apps.polling.models.election_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0004_remove_election_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="access_code",
            field=models.CharField(default=apps.polling.models.election_model.election_code_generator, editable=False, max_length=8, verbose_name="Access Code"),
        ),
    ]
